# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teleopdialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(783, 712)
        self.gridLayout_13 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.bot_checkBox_5 = QtWidgets.QCheckBox(self.groupBox_7)
        self.bot_checkBox_5.setObjectName("bot_checkBox_5")
        self.gridLayout_5.addWidget(self.bot_checkBox_5, 0, 0, 1, 1)
        self.bot_comboBox_5 = QtWidgets.QComboBox(self.groupBox_7)
        self.bot_comboBox_5.setObjectName("bot_comboBox_5")
        self.gridLayout_5.addWidget(self.bot_comboBox_5, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.bot_doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.bot_doubleSpinBox_5.setMinimum(-100.0)
        self.bot_doubleSpinBox_5.setMaximum(100.0)
        self.bot_doubleSpinBox_5.setObjectName("bot_doubleSpinBox_5")
        self.gridLayout_5.addWidget(self.bot_doubleSpinBox_5, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 3, 0, 1, 1)
        self.bot_angle_rate_doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.bot_angle_rate_doubleSpinBox_5.setMinimum(-100.0)
        self.bot_angle_rate_doubleSpinBox_5.setMaximum(100.0)
        self.bot_angle_rate_doubleSpinBox_5.setObjectName("bot_angle_rate_doubleSpinBox_5")
        self.gridLayout_5.addWidget(self.bot_angle_rate_doubleSpinBox_5, 3, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_7, 4, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bot_doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.bot_doubleSpinBox_3.setMinimum(-100.0)
        self.bot_doubleSpinBox_3.setMaximum(100.0)
        self.bot_doubleSpinBox_3.setObjectName("bot_doubleSpinBox_3")
        self.gridLayout_3.addWidget(self.bot_doubleSpinBox_3, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.bot_comboBox_3 = QtWidgets.QComboBox(self.groupBox_5)
        self.bot_comboBox_3.setObjectName("bot_comboBox_3")
        self.gridLayout_3.addWidget(self.bot_comboBox_3, 0, 1, 1, 1)
        self.bot_checkBox_3 = QtWidgets.QCheckBox(self.groupBox_5)
        self.bot_checkBox_3.setObjectName("bot_checkBox_3")
        self.gridLayout_3.addWidget(self.bot_checkBox_3, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.bot_angle_rate_doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.bot_angle_rate_doubleSpinBox_3.setMinimum(-100.0)
        self.bot_angle_rate_doubleSpinBox_3.setMaximum(100.0)
        self.bot_angle_rate_doubleSpinBox_3.setObjectName("bot_angle_rate_doubleSpinBox_3")
        self.gridLayout_3.addWidget(self.bot_angle_rate_doubleSpinBox_3, 3, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.bot_doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.bot_doubleSpinBox_1.setMinimum(-100.0)
        self.bot_doubleSpinBox_1.setMaximum(100.0)
        self.bot_doubleSpinBox_1.setObjectName("bot_doubleSpinBox_1")
        self.gridLayout.addWidget(self.bot_doubleSpinBox_1, 1, 1, 1, 1)
        self.bot_checkBox_1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.bot_checkBox_1.setObjectName("bot_checkBox_1")
        self.gridLayout.addWidget(self.bot_checkBox_1, 0, 0, 1, 1)
        self.bot_comboBox_1 = QtWidgets.QComboBox(self.groupBox_3)
        self.bot_comboBox_1.setObjectName("bot_comboBox_1")
        self.gridLayout.addWidget(self.bot_comboBox_1, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.bot_angle_rate_doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.bot_angle_rate_doubleSpinBox_1.setMinimum(-100.0)
        self.bot_angle_rate_doubleSpinBox_1.setMaximum(100.0)
        self.bot_angle_rate_doubleSpinBox_1.setObjectName("bot_angle_rate_doubleSpinBox_1")
        self.gridLayout.addWidget(self.bot_angle_rate_doubleSpinBox_1, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.bot_checkBox_4 = QtWidgets.QCheckBox(self.groupBox_6)
        self.bot_checkBox_4.setObjectName("bot_checkBox_4")
        self.gridLayout_4.addWidget(self.bot_checkBox_4, 0, 0, 1, 1)
        self.bot_comboBox_4 = QtWidgets.QComboBox(self.groupBox_6)
        self.bot_comboBox_4.setObjectName("bot_comboBox_4")
        self.gridLayout_4.addWidget(self.bot_comboBox_4, 0, 1, 1, 1)
        self.bot_doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.bot_doubleSpinBox_4.setMinimum(-100.0)
        self.bot_doubleSpinBox_4.setMaximum(100.0)
        self.bot_doubleSpinBox_4.setObjectName("bot_doubleSpinBox_4")
        self.gridLayout_4.addWidget(self.bot_doubleSpinBox_4, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 3, 0, 1, 1)
        self.bot_angle_rate_doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.bot_angle_rate_doubleSpinBox_4.setMinimum(-100.0)
        self.bot_angle_rate_doubleSpinBox_4.setMaximum(100.0)
        self.bot_angle_rate_doubleSpinBox_4.setObjectName("bot_angle_rate_doubleSpinBox_4")
        self.gridLayout_4.addWidget(self.bot_angle_rate_doubleSpinBox_4, 3, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.bot_checkBox_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.bot_checkBox_2.setObjectName("bot_checkBox_2")
        self.gridLayout_2.addWidget(self.bot_checkBox_2, 0, 0, 1, 1)
        self.bot_comboBox_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.bot_comboBox_2.setObjectName("bot_comboBox_2")
        self.gridLayout_2.addWidget(self.bot_comboBox_2, 0, 1, 1, 1)
        self.bot_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.bot_doubleSpinBox_2.setMinimum(-100.0)
        self.bot_doubleSpinBox_2.setMaximum(100.0)
        self.bot_doubleSpinBox_2.setObjectName("bot_doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.bot_doubleSpinBox_2, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.bot_angle_rate_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.bot_angle_rate_doubleSpinBox_2.setMinimum(-100.0)
        self.bot_angle_rate_doubleSpinBox_2.setMaximum(100.0)
        self.bot_angle_rate_doubleSpinBox_2.setObjectName("bot_angle_rate_doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.bot_angle_rate_doubleSpinBox_2, 3, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox, 0, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.foe_checkBox_1 = QtWidgets.QCheckBox(self.groupBox_8)
        self.foe_checkBox_1.setObjectName("foe_checkBox_1")
        self.gridLayout_6.addWidget(self.foe_checkBox_1, 0, 0, 1, 1)
        self.foe_comboBox_1 = QtWidgets.QComboBox(self.groupBox_8)
        self.foe_comboBox_1.setObjectName("foe_comboBox_1")
        self.gridLayout_6.addWidget(self.foe_comboBox_1, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_8)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.foe_doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.foe_doubleSpinBox_1.setMinimum(-100.0)
        self.foe_doubleSpinBox_1.setMaximum(100.0)
        self.foe_doubleSpinBox_1.setObjectName("foe_doubleSpinBox_1")
        self.gridLayout_6.addWidget(self.foe_doubleSpinBox_1, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 2, 0, 1, 1)
        self.foe_angle_rate_doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.foe_angle_rate_doubleSpinBox_1.setMinimum(-100.0)
        self.foe_angle_rate_doubleSpinBox_1.setMaximum(100.0)
        self.foe_angle_rate_doubleSpinBox_1.setObjectName("foe_angle_rate_doubleSpinBox_1")
        self.gridLayout_6.addWidget(self.foe_angle_rate_doubleSpinBox_1, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.foe_checkBox_2 = QtWidgets.QCheckBox(self.groupBox_9)
        self.foe_checkBox_2.setObjectName("foe_checkBox_2")
        self.gridLayout_8.addWidget(self.foe_checkBox_2, 0, 0, 1, 1)
        self.foe_comboBox_2 = QtWidgets.QComboBox(self.groupBox_9)
        self.foe_comboBox_2.setObjectName("foe_comboBox_2")
        self.gridLayout_8.addWidget(self.foe_comboBox_2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 1, 0, 1, 1)
        self.foe_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.foe_doubleSpinBox_2.setMinimum(-100.0)
        self.foe_doubleSpinBox_2.setMaximum(100.0)
        self.foe_doubleSpinBox_2.setObjectName("foe_doubleSpinBox_2")
        self.gridLayout_8.addWidget(self.foe_doubleSpinBox_2, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_9)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 2, 0, 1, 1)
        self.foe_angle_rate_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.foe_angle_rate_doubleSpinBox_2.setMinimum(-100.0)
        self.foe_angle_rate_doubleSpinBox_2.setMaximum(100.0)
        self.foe_angle_rate_doubleSpinBox_2.setObjectName("foe_angle_rate_doubleSpinBox_2")
        self.gridLayout_8.addWidget(self.foe_angle_rate_doubleSpinBox_2, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.foe_checkBox_3 = QtWidgets.QCheckBox(self.groupBox_10)
        self.foe_checkBox_3.setObjectName("foe_checkBox_3")
        self.gridLayout_9.addWidget(self.foe_checkBox_3, 0, 0, 1, 1)
        self.foe_comboBox_3 = QtWidgets.QComboBox(self.groupBox_10)
        self.foe_comboBox_3.setObjectName("foe_comboBox_3")
        self.gridLayout_9.addWidget(self.foe_comboBox_3, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_10)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 1, 0, 1, 1)
        self.foe_doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.foe_doubleSpinBox_3.setMinimum(-100.0)
        self.foe_doubleSpinBox_3.setMaximum(100.0)
        self.foe_doubleSpinBox_3.setObjectName("foe_doubleSpinBox_3")
        self.gridLayout_9.addWidget(self.foe_doubleSpinBox_3, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_10)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 2, 0, 1, 1)
        self.foe_angle_rate_doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.foe_angle_rate_doubleSpinBox_3.setMinimum(-100.0)
        self.foe_angle_rate_doubleSpinBox_3.setMaximum(100.0)
        self.foe_angle_rate_doubleSpinBox_3.setObjectName("foe_angle_rate_doubleSpinBox_3")
        self.gridLayout_9.addWidget(self.foe_angle_rate_doubleSpinBox_3, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_10, 2, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.foe_checkBox_4 = QtWidgets.QCheckBox(self.groupBox_11)
        self.foe_checkBox_4.setObjectName("foe_checkBox_4")
        self.gridLayout_10.addWidget(self.foe_checkBox_4, 0, 0, 1, 1)
        self.foe_comboBox_4 = QtWidgets.QComboBox(self.groupBox_11)
        self.foe_comboBox_4.setObjectName("foe_comboBox_4")
        self.gridLayout_10.addWidget(self.foe_comboBox_4, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_11)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 1, 0, 1, 1)
        self.foe_doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.foe_doubleSpinBox_4.setMinimum(-100.0)
        self.foe_doubleSpinBox_4.setMaximum(100.0)
        self.foe_doubleSpinBox_4.setObjectName("foe_doubleSpinBox_4")
        self.gridLayout_10.addWidget(self.foe_doubleSpinBox_4, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_11)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 2, 0, 1, 1)
        self.foe_angle_rate_doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.foe_angle_rate_doubleSpinBox_4.setMinimum(-100.0)
        self.foe_angle_rate_doubleSpinBox_4.setMaximum(100.0)
        self.foe_angle_rate_doubleSpinBox_4.setObjectName("foe_angle_rate_doubleSpinBox_4")
        self.gridLayout_10.addWidget(self.foe_angle_rate_doubleSpinBox_4, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_11, 3, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.foe_checkBox_5 = QtWidgets.QCheckBox(self.groupBox_12)
        self.foe_checkBox_5.setObjectName("foe_checkBox_5")
        self.gridLayout_11.addWidget(self.foe_checkBox_5, 0, 0, 1, 1)
        self.foe_comboBox_5 = QtWidgets.QComboBox(self.groupBox_12)
        self.foe_comboBox_5.setObjectName("foe_comboBox_5")
        self.gridLayout_11.addWidget(self.foe_comboBox_5, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_12)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 1, 0, 1, 1)
        self.foe_doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.foe_doubleSpinBox_5.setMinimum(-100.0)
        self.foe_doubleSpinBox_5.setMaximum(100.0)
        self.foe_doubleSpinBox_5.setObjectName("foe_doubleSpinBox_5")
        self.gridLayout_11.addWidget(self.foe_doubleSpinBox_5, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_12)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 2, 0, 1, 1)
        self.foe_angle_rate_doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.foe_angle_rate_doubleSpinBox_5.setMinimum(-100.0)
        self.foe_angle_rate_doubleSpinBox_5.setMaximum(100.0)
        self.foe_angle_rate_doubleSpinBox_5.setObjectName("foe_angle_rate_doubleSpinBox_5")
        self.gridLayout_11.addWidget(self.foe_angle_rate_doubleSpinBox_5, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_12, 4, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_2, 0, 1, 2, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_13)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_14.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_13, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 338, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Bot"))
        self.groupBox_7.setTitle(_translate("Dialog", "Robot 5"))
        self.bot_checkBox_5.setText(_translate("Dialog", "enabled"))
        self.label_5.setText(_translate("Dialog", "vm"))
        self.label_15.setText(_translate("Dialog", "angle rate"))
        self.groupBox_5.setTitle(_translate("Dialog", "Robot 3"))
        self.label_3.setText(_translate("Dialog", "vm"))
        self.bot_checkBox_3.setText(_translate("Dialog", "enabled"))
        self.label_13.setText(_translate("Dialog", "angle rate"))
        self.groupBox_3.setTitle(_translate("Dialog", "Robot 1"))
        self.label.setText(_translate("Dialog", "vm"))
        self.bot_checkBox_1.setText(_translate("Dialog", "enabled"))
        self.label_11.setText(_translate("Dialog", "angle rate"))
        self.groupBox_6.setTitle(_translate("Dialog", "Robot 4"))
        self.label_4.setText(_translate("Dialog", "vm"))
        self.bot_checkBox_4.setText(_translate("Dialog", "enabled"))
        self.label_14.setText(_translate("Dialog", "angle rate"))
        self.groupBox_4.setTitle(_translate("Dialog", "Robot 2"))
        self.label_2.setText(_translate("Dialog", "vm"))
        self.bot_checkBox_2.setText(_translate("Dialog", "enabled"))
        self.label_12.setText(_translate("Dialog", "angle rate"))
        self.groupBox_2.setTitle(_translate("Dialog", "Foe"))
        self.groupBox_8.setTitle(_translate("Dialog", "Foe 1"))
        self.foe_checkBox_1.setText(_translate("Dialog", "enabled"))
        self.label_6.setText(_translate("Dialog", "vm"))
        self.label_16.setText(_translate("Dialog", "angle rate"))
        self.groupBox_9.setTitle(_translate("Dialog", "Foe 1"))
        self.foe_checkBox_2.setText(_translate("Dialog", "enabled"))
        self.label_7.setText(_translate("Dialog", "vm"))
        self.label_17.setText(_translate("Dialog", "angle rate"))
        self.groupBox_10.setTitle(_translate("Dialog", "Foe 1"))
        self.foe_checkBox_3.setText(_translate("Dialog", "enabled"))
        self.label_8.setText(_translate("Dialog", "vm"))
        self.label_18.setText(_translate("Dialog", "angle rate"))
        self.groupBox_11.setTitle(_translate("Dialog", "Foe 1"))
        self.foe_checkBox_4.setText(_translate("Dialog", "enabled"))
        self.label_9.setText(_translate("Dialog", "vm"))
        self.label_19.setText(_translate("Dialog", "angle rate"))
        self.groupBox_12.setTitle(_translate("Dialog", "Foe 1"))
        self.foe_checkBox_5.setText(_translate("Dialog", "enabled"))
        self.label_10.setText(_translate("Dialog", "vm"))
        self.label_20.setText(_translate("Dialog", "angle rate"))
        self.groupBox_13.setTitle(_translate("Dialog", "Master"))

