# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teleopdialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1068, 871)
        self.gridLayout_16 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.bot_doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_doubleSpinBox_1.sizePolicy().hasHeightForWidth())
        self.bot_doubleSpinBox_1.setSizePolicy(sizePolicy)
        self.bot_doubleSpinBox_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_doubleSpinBox_1.setMinimum(-100.0)
        self.bot_doubleSpinBox_1.setMaximum(100.0)
        self.bot_doubleSpinBox_1.setObjectName("bot_doubleSpinBox_1")
        self.gridLayout.addWidget(self.bot_doubleSpinBox_1, 1, 1, 1, 1)
        self.bot_checkBox_1 = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_checkBox_1.sizePolicy().hasHeightForWidth())
        self.bot_checkBox_1.setSizePolicy(sizePolicy)
        self.bot_checkBox_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_checkBox_1.setObjectName("bot_checkBox_1")
        self.gridLayout.addWidget(self.bot_checkBox_1, 0, 0, 1, 1)
        self.bot_comboBox_1 = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_comboBox_1.sizePolicy().hasHeightForWidth())
        self.bot_comboBox_1.setSizePolicy(sizePolicy)
        self.bot_comboBox_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_comboBox_1.setObjectName("bot_comboBox_1")
        self.gridLayout.addWidget(self.bot_comboBox_1, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.bot_angle_rate_doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_angle_rate_doubleSpinBox_1.sizePolicy().hasHeightForWidth())
        self.bot_angle_rate_doubleSpinBox_1.setSizePolicy(sizePolicy)
        self.bot_angle_rate_doubleSpinBox_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_angle_rate_doubleSpinBox_1.setMinimum(-100.0)
        self.bot_angle_rate_doubleSpinBox_1.setMaximum(100.0)
        self.bot_angle_rate_doubleSpinBox_1.setObjectName("bot_angle_rate_doubleSpinBox_1")
        self.gridLayout.addWidget(self.bot_angle_rate_doubleSpinBox_1, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.bot_checkBox_2 = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_checkBox_2.sizePolicy().hasHeightForWidth())
        self.bot_checkBox_2.setSizePolicy(sizePolicy)
        self.bot_checkBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_checkBox_2.setObjectName("bot_checkBox_2")
        self.gridLayout_2.addWidget(self.bot_checkBox_2, 0, 0, 1, 1)
        self.bot_comboBox_2 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_comboBox_2.sizePolicy().hasHeightForWidth())
        self.bot_comboBox_2.setSizePolicy(sizePolicy)
        self.bot_comboBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_comboBox_2.setObjectName("bot_comboBox_2")
        self.gridLayout_2.addWidget(self.bot_comboBox_2, 0, 1, 1, 1)
        self.bot_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.bot_doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.bot_doubleSpinBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_doubleSpinBox_2.setMinimum(-100.0)
        self.bot_doubleSpinBox_2.setMaximum(100.0)
        self.bot_doubleSpinBox_2.setObjectName("bot_doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.bot_doubleSpinBox_2, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.bot_angle_rate_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_angle_rate_doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.bot_angle_rate_doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.bot_angle_rate_doubleSpinBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_angle_rate_doubleSpinBox_2.setMinimum(-100.0)
        self.bot_angle_rate_doubleSpinBox_2.setMaximum(100.0)
        self.bot_angle_rate_doubleSpinBox_2.setObjectName("bot_angle_rate_doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.bot_angle_rate_doubleSpinBox_2, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bot_doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.bot_doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.bot_doubleSpinBox_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_doubleSpinBox_3.setMinimum(-100.0)
        self.bot_doubleSpinBox_3.setMaximum(100.0)
        self.bot_doubleSpinBox_3.setObjectName("bot_doubleSpinBox_3")
        self.gridLayout_3.addWidget(self.bot_doubleSpinBox_3, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.bot_comboBox_3 = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_comboBox_3.sizePolicy().hasHeightForWidth())
        self.bot_comboBox_3.setSizePolicy(sizePolicy)
        self.bot_comboBox_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_comboBox_3.setObjectName("bot_comboBox_3")
        self.gridLayout_3.addWidget(self.bot_comboBox_3, 0, 1, 1, 1)
        self.bot_checkBox_3 = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_checkBox_3.sizePolicy().hasHeightForWidth())
        self.bot_checkBox_3.setSizePolicy(sizePolicy)
        self.bot_checkBox_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_checkBox_3.setObjectName("bot_checkBox_3")
        self.gridLayout_3.addWidget(self.bot_checkBox_3, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.bot_angle_rate_doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_angle_rate_doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.bot_angle_rate_doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.bot_angle_rate_doubleSpinBox_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_angle_rate_doubleSpinBox_3.setMinimum(-100.0)
        self.bot_angle_rate_doubleSpinBox_3.setMaximum(100.0)
        self.bot_angle_rate_doubleSpinBox_3.setObjectName("bot_angle_rate_doubleSpinBox_3")
        self.gridLayout_3.addWidget(self.bot_angle_rate_doubleSpinBox_3, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.bot_checkBox_4 = QtWidgets.QCheckBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_checkBox_4.sizePolicy().hasHeightForWidth())
        self.bot_checkBox_4.setSizePolicy(sizePolicy)
        self.bot_checkBox_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_checkBox_4.setObjectName("bot_checkBox_4")
        self.gridLayout_4.addWidget(self.bot_checkBox_4, 0, 0, 1, 1)
        self.bot_comboBox_4 = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_comboBox_4.sizePolicy().hasHeightForWidth())
        self.bot_comboBox_4.setSizePolicy(sizePolicy)
        self.bot_comboBox_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_comboBox_4.setObjectName("bot_comboBox_4")
        self.gridLayout_4.addWidget(self.bot_comboBox_4, 0, 1, 1, 1)
        self.bot_doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.bot_doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.bot_doubleSpinBox_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_doubleSpinBox_4.setMinimum(-100.0)
        self.bot_doubleSpinBox_4.setMaximum(100.0)
        self.bot_doubleSpinBox_4.setObjectName("bot_doubleSpinBox_4")
        self.gridLayout_4.addWidget(self.bot_doubleSpinBox_4, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 3, 0, 1, 1)
        self.bot_angle_rate_doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_angle_rate_doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.bot_angle_rate_doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.bot_angle_rate_doubleSpinBox_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_angle_rate_doubleSpinBox_4.setMinimum(-100.0)
        self.bot_angle_rate_doubleSpinBox_4.setMaximum(100.0)
        self.bot_angle_rate_doubleSpinBox_4.setObjectName("bot_angle_rate_doubleSpinBox_4")
        self.gridLayout_4.addWidget(self.bot_angle_rate_doubleSpinBox_4, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.bot_checkBox_5 = QtWidgets.QCheckBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_checkBox_5.sizePolicy().hasHeightForWidth())
        self.bot_checkBox_5.setSizePolicy(sizePolicy)
        self.bot_checkBox_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_checkBox_5.setObjectName("bot_checkBox_5")
        self.gridLayout_5.addWidget(self.bot_checkBox_5, 0, 0, 1, 1)
        self.bot_comboBox_5 = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_comboBox_5.sizePolicy().hasHeightForWidth())
        self.bot_comboBox_5.setSizePolicy(sizePolicy)
        self.bot_comboBox_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_comboBox_5.setObjectName("bot_comboBox_5")
        self.gridLayout_5.addWidget(self.bot_comboBox_5, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.bot_doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.bot_doubleSpinBox_5.setSizePolicy(sizePolicy)
        self.bot_doubleSpinBox_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_doubleSpinBox_5.setMinimum(-100.0)
        self.bot_doubleSpinBox_5.setMaximum(100.0)
        self.bot_doubleSpinBox_5.setObjectName("bot_doubleSpinBox_5")
        self.gridLayout_5.addWidget(self.bot_doubleSpinBox_5, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 3, 0, 1, 1)
        self.bot_angle_rate_doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_angle_rate_doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.bot_angle_rate_doubleSpinBox_5.setSizePolicy(sizePolicy)
        self.bot_angle_rate_doubleSpinBox_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bot_angle_rate_doubleSpinBox_5.setMinimum(-100.0)
        self.bot_angle_rate_doubleSpinBox_5.setMaximum(100.0)
        self.bot_angle_rate_doubleSpinBox_5.setObjectName("bot_angle_rate_doubleSpinBox_5")
        self.gridLayout_5.addWidget(self.bot_angle_rate_doubleSpinBox_5, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_7)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.foe_checkBox_5 = QtWidgets.QCheckBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_checkBox_5.sizePolicy().hasHeightForWidth())
        self.foe_checkBox_5.setSizePolicy(sizePolicy)
        self.foe_checkBox_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_checkBox_5.setObjectName("foe_checkBox_5")
        self.gridLayout_11.addWidget(self.foe_checkBox_5, 0, 0, 1, 1)
        self.foe_comboBox_5 = QtWidgets.QComboBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_comboBox_5.sizePolicy().hasHeightForWidth())
        self.foe_comboBox_5.setSizePolicy(sizePolicy)
        self.foe_comboBox_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_comboBox_5.setObjectName("foe_comboBox_5")
        self.gridLayout_11.addWidget(self.foe_comboBox_5, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 1, 0, 1, 1)
        self.foe_doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.foe_doubleSpinBox_5.setSizePolicy(sizePolicy)
        self.foe_doubleSpinBox_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_doubleSpinBox_5.setMinimum(-100.0)
        self.foe_doubleSpinBox_5.setMaximum(100.0)
        self.foe_doubleSpinBox_5.setObjectName("foe_doubleSpinBox_5")
        self.gridLayout_11.addWidget(self.foe_doubleSpinBox_5, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 2, 0, 1, 1)
        self.foe_angle_rate_doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_angle_rate_doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.foe_angle_rate_doubleSpinBox_5.setSizePolicy(sizePolicy)
        self.foe_angle_rate_doubleSpinBox_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_angle_rate_doubleSpinBox_5.setMinimum(-100.0)
        self.foe_angle_rate_doubleSpinBox_5.setMaximum(100.0)
        self.foe_angle_rate_doubleSpinBox_5.setObjectName("foe_angle_rate_doubleSpinBox_5")
        self.gridLayout_11.addWidget(self.foe_angle_rate_doubleSpinBox_5, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_12, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.foe_checkBox_4 = QtWidgets.QCheckBox(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_checkBox_4.sizePolicy().hasHeightForWidth())
        self.foe_checkBox_4.setSizePolicy(sizePolicy)
        self.foe_checkBox_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_checkBox_4.setObjectName("foe_checkBox_4")
        self.gridLayout_10.addWidget(self.foe_checkBox_4, 0, 0, 1, 1)
        self.foe_comboBox_4 = QtWidgets.QComboBox(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_comboBox_4.sizePolicy().hasHeightForWidth())
        self.foe_comboBox_4.setSizePolicy(sizePolicy)
        self.foe_comboBox_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_comboBox_4.setObjectName("foe_comboBox_4")
        self.gridLayout_10.addWidget(self.foe_comboBox_4, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 1, 0, 1, 1)
        self.foe_doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.foe_doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.foe_doubleSpinBox_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_doubleSpinBox_4.setMinimum(-100.0)
        self.foe_doubleSpinBox_4.setMaximum(100.0)
        self.foe_doubleSpinBox_4.setObjectName("foe_doubleSpinBox_4")
        self.gridLayout_10.addWidget(self.foe_doubleSpinBox_4, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 2, 0, 1, 1)
        self.foe_angle_rate_doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_angle_rate_doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.foe_angle_rate_doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.foe_angle_rate_doubleSpinBox_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_angle_rate_doubleSpinBox_4.setMinimum(-100.0)
        self.foe_angle_rate_doubleSpinBox_4.setMaximum(100.0)
        self.foe_angle_rate_doubleSpinBox_4.setObjectName("foe_angle_rate_doubleSpinBox_4")
        self.gridLayout_10.addWidget(self.foe_angle_rate_doubleSpinBox_4, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.foe_checkBox_3 = QtWidgets.QCheckBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_checkBox_3.sizePolicy().hasHeightForWidth())
        self.foe_checkBox_3.setSizePolicy(sizePolicy)
        self.foe_checkBox_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_checkBox_3.setObjectName("foe_checkBox_3")
        self.gridLayout_9.addWidget(self.foe_checkBox_3, 0, 0, 1, 1)
        self.foe_comboBox_3 = QtWidgets.QComboBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_comboBox_3.sizePolicy().hasHeightForWidth())
        self.foe_comboBox_3.setSizePolicy(sizePolicy)
        self.foe_comboBox_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_comboBox_3.setObjectName("foe_comboBox_3")
        self.gridLayout_9.addWidget(self.foe_comboBox_3, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 1, 0, 1, 1)
        self.foe_doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.foe_doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.foe_doubleSpinBox_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_doubleSpinBox_3.setMinimum(-100.0)
        self.foe_doubleSpinBox_3.setMaximum(100.0)
        self.foe_doubleSpinBox_3.setObjectName("foe_doubleSpinBox_3")
        self.gridLayout_9.addWidget(self.foe_doubleSpinBox_3, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 2, 0, 1, 1)
        self.foe_angle_rate_doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_angle_rate_doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.foe_angle_rate_doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.foe_angle_rate_doubleSpinBox_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_angle_rate_doubleSpinBox_3.setMinimum(-100.0)
        self.foe_angle_rate_doubleSpinBox_3.setMaximum(100.0)
        self.foe_angle_rate_doubleSpinBox_3.setObjectName("foe_angle_rate_doubleSpinBox_3")
        self.gridLayout_9.addWidget(self.foe_angle_rate_doubleSpinBox_3, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_10, 0, 2, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.foe_checkBox_2 = QtWidgets.QCheckBox(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_checkBox_2.sizePolicy().hasHeightForWidth())
        self.foe_checkBox_2.setSizePolicy(sizePolicy)
        self.foe_checkBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_checkBox_2.setObjectName("foe_checkBox_2")
        self.gridLayout_8.addWidget(self.foe_checkBox_2, 0, 0, 1, 1)
        self.foe_comboBox_2 = QtWidgets.QComboBox(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_comboBox_2.sizePolicy().hasHeightForWidth())
        self.foe_comboBox_2.setSizePolicy(sizePolicy)
        self.foe_comboBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_comboBox_2.setObjectName("foe_comboBox_2")
        self.gridLayout_8.addWidget(self.foe_comboBox_2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 1, 0, 1, 1)
        self.foe_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.foe_doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.foe_doubleSpinBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_doubleSpinBox_2.setMinimum(-100.0)
        self.foe_doubleSpinBox_2.setMaximum(100.0)
        self.foe_doubleSpinBox_2.setObjectName("foe_doubleSpinBox_2")
        self.gridLayout_8.addWidget(self.foe_doubleSpinBox_2, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 2, 0, 1, 1)
        self.foe_angle_rate_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_angle_rate_doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.foe_angle_rate_doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.foe_angle_rate_doubleSpinBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_angle_rate_doubleSpinBox_2.setMinimum(-100.0)
        self.foe_angle_rate_doubleSpinBox_2.setMaximum(100.0)
        self.foe_angle_rate_doubleSpinBox_2.setObjectName("foe_angle_rate_doubleSpinBox_2")
        self.gridLayout_8.addWidget(self.foe_angle_rate_doubleSpinBox_2, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_9, 0, 3, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.foe_checkBox_1 = QtWidgets.QCheckBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_checkBox_1.sizePolicy().hasHeightForWidth())
        self.foe_checkBox_1.setSizePolicy(sizePolicy)
        self.foe_checkBox_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_checkBox_1.setObjectName("foe_checkBox_1")
        self.gridLayout_6.addWidget(self.foe_checkBox_1, 0, 0, 1, 1)
        self.foe_comboBox_1 = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_comboBox_1.sizePolicy().hasHeightForWidth())
        self.foe_comboBox_1.setSizePolicy(sizePolicy)
        self.foe_comboBox_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_comboBox_1.setObjectName("foe_comboBox_1")
        self.gridLayout_6.addWidget(self.foe_comboBox_1, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.foe_doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_doubleSpinBox_1.sizePolicy().hasHeightForWidth())
        self.foe_doubleSpinBox_1.setSizePolicy(sizePolicy)
        self.foe_doubleSpinBox_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_doubleSpinBox_1.setMinimum(-100.0)
        self.foe_doubleSpinBox_1.setMaximum(100.0)
        self.foe_doubleSpinBox_1.setObjectName("foe_doubleSpinBox_1")
        self.gridLayout_6.addWidget(self.foe_doubleSpinBox_1, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 2, 0, 1, 1)
        self.foe_angle_rate_doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foe_angle_rate_doubleSpinBox_1.sizePolicy().hasHeightForWidth())
        self.foe_angle_rate_doubleSpinBox_1.setSizePolicy(sizePolicy)
        self.foe_angle_rate_doubleSpinBox_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.foe_angle_rate_doubleSpinBox_1.setMinimum(-100.0)
        self.foe_angle_rate_doubleSpinBox_1.setMaximum(100.0)
        self.foe_angle_rate_doubleSpinBox_1.setObjectName("foe_angle_rate_doubleSpinBox_1")
        self.gridLayout_6.addWidget(self.foe_angle_rate_doubleSpinBox_1, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_8, 0, 4, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_14 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_14.setMinimumSize(QtCore.QSize(500, 500))
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem, 0, 0, 1, 1)
        self.wp_comboBox = QtWidgets.QComboBox(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wp_comboBox.sizePolicy().hasHeightForWidth())
        self.wp_comboBox.setSizePolicy(sizePolicy)
        self.wp_comboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.wp_comboBox.setObjectName("wp_comboBox")
        self.gridLayout_15.addWidget(self.wp_comboBox, 0, 3, 1, 1)
        self.wp_setBtn = QtWidgets.QPushButton(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wp_setBtn.sizePolicy().hasHeightForWidth())
        self.wp_setBtn.setSizePolicy(sizePolicy)
        self.wp_setBtn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.wp_setBtn.setObjectName("wp_setBtn")
        self.gridLayout_15.addWidget(self.wp_setBtn, 0, 4, 1, 1)
        self.wp_clearBtn = QtWidgets.QPushButton(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wp_clearBtn.sizePolicy().hasHeightForWidth())
        self.wp_clearBtn.setSizePolicy(sizePolicy)
        self.wp_clearBtn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.wp_clearBtn.setObjectName("wp_clearBtn")
        self.gridLayout_15.addWidget(self.wp_clearBtn, 0, 5, 1, 1)
        self.wp_graphicsView = QtWidgets.QGraphicsView(self.groupBox_14)
        self.wp_graphicsView.setObjectName("wp_graphicsView")
        self.gridLayout_15.addWidget(self.wp_graphicsView, 1, 0, 1, 6)
        self.load_btn = QtWidgets.QPushButton(self.groupBox_14)
        self.load_btn.setObjectName("load_btn")
        self.gridLayout_15.addWidget(self.load_btn, 0, 2, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.groupBox_14)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_15.addWidget(self.save_btn, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_13 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_13.setMinimumSize(QtCore.QSize(350, 350))
        self.groupBox_13.setMaximumSize(QtCore.QSize(400, 400))
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_13)
        self.graphicsView.setMaximumSize(QtCore.QSize(400, 16777215))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.gridLayout_14.addWidget(self.groupBox_13, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_16.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Bot"))
        self.groupBox_3.setTitle(_translate("Dialog", "Robot 1"))
        self.label.setText(_translate("Dialog", "vm"))
        self.bot_checkBox_1.setText(_translate("Dialog", "enabled"))
        self.label_11.setText(_translate("Dialog", "angle rate"))
        self.groupBox_4.setTitle(_translate("Dialog", "Robot 2"))
        self.label_2.setText(_translate("Dialog", "vm"))
        self.bot_checkBox_2.setText(_translate("Dialog", "enabled"))
        self.label_12.setText(_translate("Dialog", "angle rate"))
        self.groupBox_5.setTitle(_translate("Dialog", "Robot 3"))
        self.label_3.setText(_translate("Dialog", "vm"))
        self.bot_checkBox_3.setText(_translate("Dialog", "enabled"))
        self.label_13.setText(_translate("Dialog", "angle rate"))
        self.groupBox_6.setTitle(_translate("Dialog", "Robot 4"))
        self.label_4.setText(_translate("Dialog", "vm"))
        self.bot_checkBox_4.setText(_translate("Dialog", "enabled"))
        self.label_14.setText(_translate("Dialog", "angle rate"))
        self.groupBox_7.setTitle(_translate("Dialog", "Robot 5"))
        self.bot_checkBox_5.setText(_translate("Dialog", "enabled"))
        self.label_5.setText(_translate("Dialog", "vm"))
        self.label_15.setText(_translate("Dialog", "angle rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Bot"))
        self.groupBox_2.setTitle(_translate("Dialog", "Foe"))
        self.groupBox_12.setTitle(_translate("Dialog", "Foe 5"))
        self.foe_checkBox_5.setText(_translate("Dialog", "enabled"))
        self.label_10.setText(_translate("Dialog", "vm"))
        self.label_20.setText(_translate("Dialog", "angle rate"))
        self.groupBox_11.setTitle(_translate("Dialog", "Foe 4"))
        self.foe_checkBox_4.setText(_translate("Dialog", "enabled"))
        self.label_9.setText(_translate("Dialog", "vm"))
        self.label_19.setText(_translate("Dialog", "angle rate"))
        self.groupBox_10.setTitle(_translate("Dialog", "Foe 3"))
        self.foe_checkBox_3.setText(_translate("Dialog", "enabled"))
        self.label_8.setText(_translate("Dialog", "vm"))
        self.label_18.setText(_translate("Dialog", "angle rate"))
        self.groupBox_9.setTitle(_translate("Dialog", "Foe 2"))
        self.foe_checkBox_2.setText(_translate("Dialog", "enabled"))
        self.label_7.setText(_translate("Dialog", "vm"))
        self.label_17.setText(_translate("Dialog", "angle rate"))
        self.groupBox_8.setTitle(_translate("Dialog", "Foe 1"))
        self.foe_checkBox_1.setText(_translate("Dialog", "enabled"))
        self.label_6.setText(_translate("Dialog", "vm"))
        self.label_16.setText(_translate("Dialog", "angle rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Foe"))
        self.groupBox_14.setTitle(_translate("Dialog", "Waypoint"))
        self.wp_setBtn.setText(_translate("Dialog", "set"))
        self.wp_clearBtn.setText(_translate("Dialog", "clear"))
        self.load_btn.setText(_translate("Dialog", "load"))
        self.save_btn.setText(_translate("Dialog", "save"))
        self.groupBox_13.setTitle(_translate("Dialog", "Master"))

